UPDATE fiends SET id = 1 WHERE name = 'dingo';
UPDATE fiends SET id = 2 WHERE name = 'condor';
UPDATE fiends SET id = 3 WHERE name = 'budino d''acqua';
UPDATE fiends SET id = 4 WHERE name = 'deinonychus';
UPDATE fiends SET id = 5 WHERE name = 'ape killer';
UPDATE fiends SET id = 6 WHERE name = 'elemento giallo';
UPDATE fiends SET id = 7 WHERE name = 'balsamiko';
UPDATE fiends SET id = 8 WHERE name = 'mihen phang';
UPDATE fiends SET id = 9 WHERE name = 'ipiria';
UPDATE fiends SET id = 10 WHERE name = 'occhio fluttuante';
UPDATE fiends SET id = 11 WHERE name = 'elemento bianco';
UPDATE fiends SET id = 12 WHERE name = 'rarth';
UPDATE fiends SET id = 13 WHERE name = 'vivre';
UPDATE fiends SET id = 14 WHERE name = 'piros';
UPDATE fiends SET id = 15 WHERE name = 'bikorno';
UPDATE fiends SET id = 16 WHERE name = 'raptor';
UPDATE fiends SET id = 17 WHERE name = 'gandharva';
UPDATE fiends SET id = 18 WHERE name = 'budino di tuono';
UPDATE fiends SET id = 19 WHERE name = 'elemento rosso';
UPDATE fiends SET id = 20 WHERE name = 'ramashut';
UPDATE fiends SET id = 21 WHERE name = 'fungongo';
UPDATE fiends SET id = 22 WHERE name = 'garuda';
UPDATE fiends SET id = 23 WHERE name = 'garm';
UPDATE fiends SET id = 24 WHERE name = 'simurgh';
UPDATE fiends SET id = 25 WHERE name = 'lesmathor';
UPDATE fiends SET id = 26 WHERE name = 'budino di neve';
UPDATE fiends SET id = 27 WHERE name = 'bunyips';
UPDATE fiends SET id = 28 WHERE name = 'basilisk';
UPDATE fiends SET id = 29 WHERE name = 'ochu';
UPDATE fiends SET id = 30 WHERE name = 'meryujin';
UPDATE fiends SET id = 31 WHERE name = 'aroj';
UPDATE fiends SET id = 32 WHERE name = 'buel';
UPDATE fiends SET id = 33 WHERE name = 'elemento dorato';
UPDATE fiends SET id = 34 WHERE name = 'kusarik';
UPDATE fiends SET id = 35 WHERE name = 'larva';
UPDATE fiends SET id = 36 WHERE name = 'thytan';
UPDATE fiends SET id = 37 WHERE name = 'kyactus?';
UPDATE fiends SET id = 38 WHERE name = 'lupo delle nevi';
UPDATE fiends SET id = 39 WHERE name = 'shumelke';
UPDATE fiends SET id = 40 WHERE name = 'vespa';
UPDATE fiends SET id = 41 WHERE name = 'occhio diabolico';
UPDATE fiends SET id = 42 WHERE name = 'budino di ghiaccio';
UPDATE fiends SET id = 43 WHERE name = 'elemento blu';
UPDATE fiends SET id = 44 WHERE name = 'mulfus';
UPDATE fiends SET id = 45 WHERE name = 'mafut';
UPDATE fiends SET id = 46 WHERE name = 'kushipos';
UPDATE fiends SET id = 47 WHERE name = 'chimera';
UPDATE fiends SET id = 48 WHERE name = 'lupo del deserto';
UPDATE fiends SET id = 49 WHERE name = 'alcione';
UPDATE fiends SET id = 50 WHERE name = 'mushuhushu';
UPDATE fiends SET id = 51 WHERE name = 'zuu';
UPDATE fiends SET id = 52 WHERE name = 'anellidus';
UPDATE fiends SET id = 53 WHERE name = 'kyactus';
UPDATE fiends SET id = 54 WHERE name = 'scoor';
UPDATE fiends SET id = 55 WHERE name = 'nebiros';
UPDATE fiends SET id = 56 WHERE name = 'budino di fiamme';
UPDATE fiends SET id = 57 WHERE name = 'shred';
UPDATE fiends SET id = 58 WHERE name = 'anacondar';
UPDATE fiends SET id = 59 WHERE name = 'hoga';
UPDATE fiends SET id = 60 WHERE name = 'iaguaro';
UPDATE fiends SET id = 61 WHERE name = 'chimera brain';
UPDATE fiends SET id = 62 WHERE name = 'molboro';
UPDATE fiends SET id = 63 WHERE name = 'yowie';
UPDATE fiends SET id = 64 WHERE name = 'galkimasela';
UPDATE fiends SET id = 65 WHERE name = 'elemento scuro';
UPDATE fiends SET id = 66 WHERE name = 'heg';
UPDATE fiends SET id = 67 WHERE name = 'son';
UPDATE fiends SET id = 68 WHERE name = 'varaha';
UPDATE fiends SET id = 69 WHERE name = 'epej';
UPDATE fiends SET id = 70 WHERE name = 'fantasma';
UPDATE fiends SET id = 71 WHERE name = 'tomberry';
UPDATE fiends SET id = 72 WHERE name = 'mal bernardo';
UPDATE fiends SET id = 73 WHERE name = 'alyman';
UPDATE fiends SET id = 74 WHERE name = 'budino oscuro';
UPDATE fiends SET id = 75 WHERE name = 'granad';
UPDATE fiends SET id = 76 WHERE name = 'grat';
UPDATE fiends SET id = 77 WHERE name = 'grendel';
UPDATE fiends SET id = 78 WHERE name = 'ashoor';
UPDATE fiends SET id = 79 WHERE name = 'mandragora';
UPDATE fiends SET id = 80 WHERE name = 'behemoth';
UPDATE fiends SET id = 81 WHERE name = 'splasher';
UPDATE fiends SET id = 82 WHERE name = 'aquelous';
UPDATE fiends SET id = 83 WHERE name = 'echeneis';
UPDATE fiends SET id = 84 WHERE name = 'exoray';
UPDATE fiends SET id = 85 WHERE name = 'alyadin';
UPDATE fiends SET id = 86 WHERE name = 'ultra might (spada normale)';
UPDATE fiends SET id = 87 WHERE name = 'ultra might (spada stella)';
UPDATE fiends SET id = 88 WHERE name = 'demomonolix';
UPDATE fiends SET id = 89 WHERE name = 'molboro il grande';
UPDATE fiends SET id = 90 WHERE name = 'barbatos';
UPDATE fiends SET id = 91 WHERE name = 'adamanthart';
UPDATE fiends SET id = 92 WHERE name = 'king behemoth';
UPDATE fiends SET id = 93 WHERE name = 'zauras';
UPDATE fiends SET id = 94 WHERE name = 'byurobolos';
UPDATE fiends SET id = 95 WHERE name = 'desflot';
UPDATE fiends SET id = 96 WHERE name = 'elemento nero';
UPDATE fiends SET id = 97 WHERE name = 'haruma';
UPDATE fiends SET id = 98 WHERE name = 'esprit';
UPDATE fiends SET id = 99 WHERE name = 'mechy';
UPDATE fiends SET id = 100 WHERE name = 'master iaguaro';
UPDATE fiends SET id = 101 WHERE name = 'mastro tomberry';
UPDATE fiends SET id = 102 WHERE name = 'varna';