"""

Revision ID: 709b81de5e7e
Revises: 
Create Date: 2024-11-13 11:20:25.722847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709b81de5e7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mp', sa.Integer(), nullable=True),
    sa.Column('overkill', sa.Integer(), nullable=True),
    sa.Column('guil', sa.Integer(), nullable=True),
    sa.Column('ap', sa.Integer(), nullable=True),
    sa.Column('ap_overkill', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('magic', sa.Integer(), nullable=True),
    sa.Column('magic_defense', sa.Integer(), nullable=True),
    sa.Column('agility', sa.Integer(), nullable=True),
    sa.Column('luck', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('evasion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_id'), 'stats', ['id'], unique=False)
    op.create_table('weakness_or_resistance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_weakness_or_resistance_id'), 'weakness_or_resistance', ['id'], unique=False)
    op.create_table('original_creation_resistance',
    sa.Column('original_creation_id', sa.Integer(), nullable=False),
    sa.Column('resistance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_creation_id'], ['original_creations.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['resistance_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('original_creation_id', 'resistance_id')
    )
    op.create_index(op.f('ix_original_creation_resistance_original_creation_id'), 'original_creation_resistance', ['original_creation_id'], unique=False)
    op.create_index(op.f('ix_original_creation_resistance_resistance_id'), 'original_creation_resistance', ['resistance_id'], unique=False)
    op.create_table('original_creation_stats',
    sa.Column('original_creation_id', sa.Integer(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_creation_id'], ['original_creations.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('original_creation_id', 'stats_id')
    )
    op.create_index(op.f('ix_original_creation_stats_original_creation_id'), 'original_creation_stats', ['original_creation_id'], unique=False)
    op.create_index(op.f('ix_original_creation_stats_stats_id'), 'original_creation_stats', ['stats_id'], unique=False)
    op.create_table('original_creation_weakness',
    sa.Column('original_creation_id', sa.Integer(), nullable=False),
    sa.Column('weakness_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_creation_id'], ['original_creations.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['weakness_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('original_creation_id', 'weakness_id')
    )
    op.create_index(op.f('ix_original_creation_weakness_original_creation_id'), 'original_creation_weakness', ['original_creation_id'], unique=False)
    op.create_index(op.f('ix_original_creation_weakness_weakness_id'), 'original_creation_weakness', ['weakness_id'], unique=False)
    op.create_table('species_conquest_resistance',
    sa.Column('species_conquest_id', sa.Integer(), nullable=False),
    sa.Column('resistance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resistance_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['species_conquest_id'], ['species_conquests.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('species_conquest_id', 'resistance_id')
    )
    op.create_index(op.f('ix_species_conquest_resistance_resistance_id'), 'species_conquest_resistance', ['resistance_id'], unique=False)
    op.create_index(op.f('ix_species_conquest_resistance_species_conquest_id'), 'species_conquest_resistance', ['species_conquest_id'], unique=False)
    op.create_table('species_conquest_stats',
    sa.Column('species_conquest_id', sa.Integer(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_conquest_id'], ['species_conquests.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('species_conquest_id', 'stats_id')
    )
    op.create_index(op.f('ix_species_conquest_stats_species_conquest_id'), 'species_conquest_stats', ['species_conquest_id'], unique=False)
    op.create_index(op.f('ix_species_conquest_stats_stats_id'), 'species_conquest_stats', ['stats_id'], unique=False)
    op.create_table('species_conquest_weakness',
    sa.Column('species_conquest_id', sa.Integer(), nullable=False),
    sa.Column('weakness_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_conquest_id'], ['species_conquests.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['weakness_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('species_conquest_id', 'weakness_id')
    )
    op.create_index(op.f('ix_species_conquest_weakness_species_conquest_id'), 'species_conquest_weakness', ['species_conquest_id'], unique=False)
    op.create_index(op.f('ix_species_conquest_weakness_weakness_id'), 'species_conquest_weakness', ['weakness_id'], unique=False)
    op.create_table('area_conquest_resistance',
    sa.Column('area_conquest_id', sa.Integer(), nullable=False),
    sa.Column('resistance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_conquest_id'], ['area_conquests.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['resistance_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('area_conquest_id', 'resistance_id')
    )
    op.create_index(op.f('ix_area_conquest_resistance_area_conquest_id'), 'area_conquest_resistance', ['area_conquest_id'], unique=False)
    op.create_index(op.f('ix_area_conquest_resistance_resistance_id'), 'area_conquest_resistance', ['resistance_id'], unique=False)
    op.create_table('area_conquest_stats',
    sa.Column('area_conquest_id', sa.Integer(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_conquest_id'], ['area_conquests.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('area_conquest_id', 'stats_id')
    )
    op.create_index(op.f('ix_area_conquest_stats_area_conquest_id'), 'area_conquest_stats', ['area_conquest_id'], unique=False)
    op.create_index(op.f('ix_area_conquest_stats_stats_id'), 'area_conquest_stats', ['stats_id'], unique=False)
    op.create_table('area_conquest_weakness',
    sa.Column('area_conquest_id', sa.Integer(), nullable=False),
    sa.Column('weakness_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_conquest_id'], ['area_conquests.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['weakness_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('area_conquest_id', 'weakness_id')
    )
    op.create_index(op.f('ix_area_conquest_weakness_area_conquest_id'), 'area_conquest_weakness', ['area_conquest_id'], unique=False)
    op.create_index(op.f('ix_area_conquest_weakness_weakness_id'), 'area_conquest_weakness', ['weakness_id'], unique=False)
    op.create_table('fiend_resistance',
    sa.Column('fiend_id', sa.Integer(), nullable=False),
    sa.Column('resistance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fiend_id'], ['fiends.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['resistance_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('fiend_id', 'resistance_id')
    )
    op.create_index(op.f('ix_fiend_resistance_fiend_id'), 'fiend_resistance', ['fiend_id'], unique=False)
    op.create_index(op.f('ix_fiend_resistance_resistance_id'), 'fiend_resistance', ['resistance_id'], unique=False)
    op.create_table('fiend_stats',
    sa.Column('fiend_id', sa.Integer(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fiend_id'], ['fiends.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('fiend_id', 'stats_id')
    )
    op.create_index(op.f('ix_fiend_stats_fiend_id'), 'fiend_stats', ['fiend_id'], unique=False)
    op.create_index(op.f('ix_fiend_stats_stats_id'), 'fiend_stats', ['stats_id'], unique=False)
    op.create_table('fiend_weakness',
    sa.Column('fiend_id', sa.Integer(), nullable=False),
    sa.Column('weakness_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fiend_id'], ['fiends.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['weakness_id'], ['weakness_or_resistance.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('fiend_id', 'weakness_id')
    )
    op.create_index(op.f('ix_fiend_weakness_fiend_id'), 'fiend_weakness', ['fiend_id'], unique=False)
    op.create_index(op.f('ix_fiend_weakness_weakness_id'), 'fiend_weakness', ['weakness_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fiend_weakness_weakness_id'), table_name='fiend_weakness')
    op.drop_index(op.f('ix_fiend_weakness_fiend_id'), table_name='fiend_weakness')
    op.drop_table('fiend_weakness')
    op.drop_index(op.f('ix_fiend_stats_stats_id'), table_name='fiend_stats')
    op.drop_index(op.f('ix_fiend_stats_fiend_id'), table_name='fiend_stats')
    op.drop_table('fiend_stats')
    op.drop_index(op.f('ix_fiend_resistance_resistance_id'), table_name='fiend_resistance')
    op.drop_index(op.f('ix_fiend_resistance_fiend_id'), table_name='fiend_resistance')
    op.drop_table('fiend_resistance')
    op.drop_index(op.f('ix_area_conquest_weakness_weakness_id'), table_name='area_conquest_weakness')
    op.drop_index(op.f('ix_area_conquest_weakness_area_conquest_id'), table_name='area_conquest_weakness')
    op.drop_table('area_conquest_weakness')
    op.drop_index(op.f('ix_area_conquest_stats_stats_id'), table_name='area_conquest_stats')
    op.drop_index(op.f('ix_area_conquest_stats_area_conquest_id'), table_name='area_conquest_stats')
    op.drop_table('area_conquest_stats')
    op.drop_index(op.f('ix_area_conquest_resistance_resistance_id'), table_name='area_conquest_resistance')
    op.drop_index(op.f('ix_area_conquest_resistance_area_conquest_id'), table_name='area_conquest_resistance')
    op.drop_table('area_conquest_resistance')
    op.drop_index(op.f('ix_species_conquest_weakness_weakness_id'), table_name='species_conquest_weakness')
    op.drop_index(op.f('ix_species_conquest_weakness_species_conquest_id'), table_name='species_conquest_weakness')
    op.drop_table('species_conquest_weakness')
    op.drop_index(op.f('ix_species_conquest_stats_stats_id'), table_name='species_conquest_stats')
    op.drop_index(op.f('ix_species_conquest_stats_species_conquest_id'), table_name='species_conquest_stats')
    op.drop_table('species_conquest_stats')
    op.drop_index(op.f('ix_species_conquest_resistance_species_conquest_id'), table_name='species_conquest_resistance')
    op.drop_index(op.f('ix_species_conquest_resistance_resistance_id'), table_name='species_conquest_resistance')
    op.drop_table('species_conquest_resistance')
    op.drop_index(op.f('ix_original_creation_weakness_weakness_id'), table_name='original_creation_weakness')
    op.drop_index(op.f('ix_original_creation_weakness_original_creation_id'), table_name='original_creation_weakness')
    op.drop_table('original_creation_weakness')
    op.drop_index(op.f('ix_original_creation_stats_stats_id'), table_name='original_creation_stats')
    op.drop_index(op.f('ix_original_creation_stats_original_creation_id'), table_name='original_creation_stats')
    op.drop_table('original_creation_stats')
    op.drop_index(op.f('ix_original_creation_resistance_resistance_id'), table_name='original_creation_resistance')
    op.drop_index(op.f('ix_original_creation_resistance_original_creation_id'), table_name='original_creation_resistance')
    op.drop_table('original_creation_resistance')
    op.drop_index(op.f('ix_weakness_or_resistance_id'), table_name='weakness_or_resistance')
    op.drop_table('weakness_or_resistance')
    op.drop_index(op.f('ix_stats_id'), table_name='stats')
    op.drop_table('stats')
    # ### end Alembic commands ###
