"""

Revision ID: 8aad7dc9762f
Revises: 709b81de5e7e
Create Date: 2024-11-13 17:55:50.195337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aad7dc9762f'
down_revision: Union[str, None] = '709b81de5e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('for_fiend', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'for_fiend')
    # ### end Alembic commands ###
