"""

Revision ID: d80733ba4ac9
Revises: 8aad7dc9762f
Create Date: 2024-11-14 02:09:21.655445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80733ba4ac9'
down_revision: Union[str, None] = '8aad7dc9762f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'magic_defense')
    op.drop_column('stats', 'evasion')
    op.drop_column('stats', 'luck')
    op.drop_column('stats', 'magic')
    op.drop_column('stats', 'strength')
    op.drop_column('stats', 'agility')
    op.drop_column('stats', 'defense')
    op.drop_column('stats', 'accuracy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('accuracy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('defense', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('magic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('luck', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('evasion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('magic_defense', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
