"""

Revision ID: 2ef5b51cc140
Revises: af53c13065d5
Create Date: 2024-10-24 19:02:05.350870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef5b51cc140'
down_revision: Union[str, None] = 'af53c13065d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_conquests', sa.Column('defeated', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_area_conquests_defeated'), 'area_conquests', ['defeated'], unique=False)
    op.add_column('original_creations', sa.Column('defeated', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_original_creations_defeated'), 'original_creations', ['defeated'], unique=False)
    op.add_column('species_conquests', sa.Column('defeated', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_species_conquests_defeated'), 'species_conquests', ['defeated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_conquests_defeated'), table_name='species_conquests')
    op.drop_column('species_conquests', 'defeated')
    op.drop_index(op.f('ix_original_creations_defeated'), table_name='original_creations')
    op.drop_column('original_creations', 'defeated')
    op.drop_index(op.f('ix_area_conquests_defeated'), table_name='area_conquests')
    op.drop_column('area_conquests', 'defeated')
    # ### end Alembic commands ###
