"""Aggiunta relazione can_be_found

Revision ID: 3c0a30842117
Revises: 2ef5b51cc140
Create Date: 2024-10-26 18:30:59.028268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0a30842117'
down_revision: Union[str, None] = '2ef5b51cc140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('can_be_found',
    sa.Column('fiend_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fiend_id'], ['fiends.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('fiend_id', 'zone_id')
    )
    op.create_index(op.f('ix_can_be_found_fiend_id'), 'can_be_found', ['fiend_id'], unique=False)
    op.create_index(op.f('ix_can_be_found_zone_id'), 'can_be_found', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_can_be_found_zone_id'), table_name='can_be_found')
    op.drop_index(op.f('ix_can_be_found_fiend_id'), table_name='can_be_found')
    op.drop_table('can_be_found')
    # ### end Alembic commands ###
