"""

Revision ID: 3cd498339ea3
Revises: ba02a106b342
Create Date: 2024-11-03 18:23:13.297143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd498339ea3'
down_revision: Union[str, None] = 'ba02a106b342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_types_id', table_name='item_types')
    op.drop_index('ix_item_types_name', table_name='item_types')
    op.drop_table('item_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_types_pkey')
    )
    op.create_index('ix_item_types_name', 'item_types', ['name'], unique=True)
    op.create_index('ix_item_types_id', 'item_types', ['id'], unique=False)
    # ### end Alembic commands ###
