"""

Revision ID: 42534484a5a9
Revises: e164f41ed754
Create Date: 2024-11-05 22:46:31.199988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42534484a5a9'
down_revision: Union[str, None] = 'e164f41ed754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('original_creation_rewards',
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('original_creation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['original_creation_id'], ['original_creations.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('reward_type', 'item_id', 'original_creation_id')
    )
    op.create_index(op.f('ix_original_creation_rewards_reward_type'), 'original_creation_rewards', ['reward_type'], unique=False)
    op.create_table('species_conquest_rewards',
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('species_conquest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['species_conquest_id'], ['species_conquests.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('reward_type', 'item_id', 'species_conquest_id')
    )
    op.create_index(op.f('ix_species_conquest_rewards_reward_type'), 'species_conquest_rewards', ['reward_type'], unique=False)
    op.create_table('area_conquest_rewards',
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('area_conquest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_conquest_id'], ['area_conquests.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('reward_type', 'item_id', 'area_conquest_id')
    )
    op.create_index(op.f('ix_area_conquest_rewards_reward_type'), 'area_conquest_rewards', ['reward_type'], unique=False)
    op.create_table('fiend_rewards',
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fiend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fiend_id'], ['fiends.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('reward_type', 'item_id', 'fiend_id')
    )
    op.create_index(op.f('ix_fiend_rewards_reward_type'), 'fiend_rewards', ['reward_type'], unique=False)
    op.drop_index('ix_rewards_reward_type', table_name='rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('reward_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fiend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fiend_id'], ['fiends.id'], name='rewards_fiend_id_fkey', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='rewards_item_id_fkey', onupdate='CASCADE')
    )
    op.create_index('ix_rewards_reward_type', 'rewards', ['reward_type'], unique=False)
    op.drop_index(op.f('ix_fiend_rewards_reward_type'), table_name='fiend_rewards')
    op.drop_table('fiend_rewards')
    op.drop_index(op.f('ix_area_conquest_rewards_reward_type'), table_name='area_conquest_rewards')
    op.drop_table('area_conquest_rewards')
    op.drop_index(op.f('ix_species_conquest_rewards_reward_type'), table_name='species_conquest_rewards')
    op.drop_table('species_conquest_rewards')
    op.drop_index(op.f('ix_original_creation_rewards_reward_type'), table_name='original_creation_rewards')
    op.drop_table('original_creation_rewards')
    # ### end Alembic commands ###
