"""

Revision ID: 49d8be237efd
Revises: 05777de1aa59
Create Date: 2024-11-03 16:47:25.331918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d8be237efd'
down_revision: Union[str, None] = '05777de1aa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_abilities_id'), 'abilities', ['id'], unique=False)
    op.create_table('original_creation_equipment_rewards',
    sa.Column('original_creations_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['original_creations_id'], ['original_creations.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('original_creations_id', 'ability_id')
    )
    op.create_index(op.f('ix_original_creation_equipment_rewards_ability_id'), 'original_creation_equipment_rewards', ['ability_id'], unique=False)
    op.create_index(op.f('ix_original_creation_equipment_rewards_original_creations_id'), 'original_creation_equipment_rewards', ['original_creations_id'], unique=False)
    op.create_table('species_conquest_equipment_rewards',
    sa.Column('species_conquest_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['species_conquest_id'], ['species_conquests.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('species_conquest_id', 'ability_id')
    )
    op.create_index(op.f('ix_species_conquest_equipment_rewards_ability_id'), 'species_conquest_equipment_rewards', ['ability_id'], unique=False)
    op.create_index(op.f('ix_species_conquest_equipment_rewards_species_conquest_id'), 'species_conquest_equipment_rewards', ['species_conquest_id'], unique=False)
    op.create_table('area_conquest_equipment_rewards',
    sa.Column('area_conquest_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['area_conquest_id'], ['area_conquests.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('area_conquest_id', 'ability_id')
    )
    op.create_index(op.f('ix_area_conquest_equipment_rewards_ability_id'), 'area_conquest_equipment_rewards', ['ability_id'], unique=False)
    op.create_index(op.f('ix_area_conquest_equipment_rewards_area_conquest_id'), 'area_conquest_equipment_rewards', ['area_conquest_id'], unique=False)
    op.create_table('fiend_equipment_rewards',
    sa.Column('fiend_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['fiend_id'], ['fiends.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('fiend_id', 'ability_id')
    )
    op.create_index(op.f('ix_fiend_equipment_rewards_ability_id'), 'fiend_equipment_rewards', ['ability_id'], unique=False)
    op.create_index(op.f('ix_fiend_equipment_rewards_fiend_id'), 'fiend_equipment_rewards', ['fiend_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_index(op.f('ix_rewards_reward_type'), 'rewards', ['reward_type'], unique=False)
    op.create_table('reward_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_associations_id'), 'reward_associations', ['id'], unique=False)
    op.drop_constraint('items_type_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'item_types', ['type_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_type_id_fkey', 'items', 'item_types', ['type_id'], ['id'])
    op.drop_index(op.f('ix_reward_associations_id'), table_name='reward_associations')
    op.drop_table('reward_associations')
    op.drop_index(op.f('ix_rewards_reward_type'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_fiend_equipment_rewards_fiend_id'), table_name='fiend_equipment_rewards')
    op.drop_index(op.f('ix_fiend_equipment_rewards_ability_id'), table_name='fiend_equipment_rewards')
    op.drop_table('fiend_equipment_rewards')
    op.drop_index(op.f('ix_area_conquest_equipment_rewards_area_conquest_id'), table_name='area_conquest_equipment_rewards')
    op.drop_index(op.f('ix_area_conquest_equipment_rewards_ability_id'), table_name='area_conquest_equipment_rewards')
    op.drop_table('area_conquest_equipment_rewards')
    op.drop_index(op.f('ix_species_conquest_equipment_rewards_species_conquest_id'), table_name='species_conquest_equipment_rewards')
    op.drop_index(op.f('ix_species_conquest_equipment_rewards_ability_id'), table_name='species_conquest_equipment_rewards')
    op.drop_table('species_conquest_equipment_rewards')
    op.drop_index(op.f('ix_original_creation_equipment_rewards_original_creations_id'), table_name='original_creation_equipment_rewards')
    op.drop_index(op.f('ix_original_creation_equipment_rewards_ability_id'), table_name='original_creation_equipment_rewards')
    op.drop_table('original_creation_equipment_rewards')
    op.drop_index(op.f('ix_abilities_id'), table_name='abilities')
    op.drop_table('abilities')
    # ### end Alembic commands ###
