"""zoolab_test

Revision ID: 4f81ad83e2d8
Revises: 714bde0e09cc
Create Date: 2024-11-14 02:07:36.831980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f81ad83e2d8'
down_revision: Union[str, None] = '714bde0e09cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'luck')
    op.drop_column('stats', 'agility')
    op.drop_column('stats', 'magic_defense')
    op.drop_column('stats', 'magic')
    op.drop_column('stats', 'accuracy')
    op.drop_column('stats', 'strength')
    op.drop_column('stats', 'defense')
    op.drop_column('stats', 'evasion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('evasion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('defense', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('accuracy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('magic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('magic_defense', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('luck', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
