"""

Revision ID: 716c859e8f88
Revises: f7b82ae01f80
Create Date: 2024-11-03 14:37:39.850061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716c859e8f88'
down_revision: Union[str, None] = 'f7b82ae01f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_conquests', sa.Column('defeat_reward', sa.String(), nullable=True))
    op.add_column('area_conquests', sa.Column('commons_steal', sa.String(), nullable=True))
    op.add_column('area_conquests', sa.Column('rare_steal', sa.String(), nullable=True))
    op.add_column('original_creations', sa.Column('defeat_reward', sa.String(), nullable=True))
    op.add_column('original_creations', sa.Column('commons_steal', sa.String(), nullable=True))
    op.add_column('original_creations', sa.Column('rare_steal', sa.String(), nullable=True))
    op.add_column('species_conquests', sa.Column('defeat_reward', sa.String(), nullable=True))
    op.add_column('species_conquests', sa.Column('commons_steal', sa.String(), nullable=True))
    op.add_column('species_conquests', sa.Column('rare_steal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species_conquests', 'rare_steal')
    op.drop_column('species_conquests', 'commons_steal')
    op.drop_column('species_conquests', 'defeat_reward')
    op.drop_column('original_creations', 'rare_steal')
    op.drop_column('original_creations', 'commons_steal')
    op.drop_column('original_creations', 'defeat_reward')
    op.drop_column('area_conquests', 'rare_steal')
    op.drop_column('area_conquests', 'commons_steal')
    op.drop_column('area_conquests', 'defeat_reward')
    # ### end Alembic commands ###
