"""

Revision ID: 8edcb3b4ef8e
Revises: 5b2c44ebc3e4
Create Date: 2024-11-03 17:35:22.480703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edcb3b4ef8e'
down_revision: Union[str, None] = '5b2c44ebc3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_associations', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('rewards', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reward_associations', 'quantity')
    # ### end Alembic commands ###
