"""

Revision ID: ba02a106b342
Revises: ddc1f7d38300
Create Date: 2024-11-03 18:22:59.219384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba02a106b342'
down_revision: Union[str, None] = 'ddc1f7d38300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_type_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('items_type_id_fkey', 'items', 'item_types', ['type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
