"""migrazione

Revision ID: be361e5e4354
Revises: 
Create Date: 2024-10-23 18:12:33.784545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be361e5e4354'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('original_creations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.Column('creation_rule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_original_creations_id'), 'original_creations', ['id'], unique=False)
    op.create_index(op.f('ix_original_creations_name'), 'original_creations', ['name'], unique=True)
    op.create_table('special_fiends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_special_fiends_id'), 'special_fiends', ['id'], unique=False)
    op.create_index(op.f('ix_special_fiends_name'), 'special_fiends', ['name'], unique=True)
    op.create_table('species_conquests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('required_fiends', sa.Integer(), nullable=False),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_species_conquests_id'), 'species_conquests', ['id'], unique=False)
    op.create_index(op.f('ix_species_conquests_name'), 'species_conquests', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=True)
    op.create_table('area_conquests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_area_conquests_id'), 'area_conquests', ['id'], unique=False)
    op.create_index(op.f('ix_area_conquests_name'), 'area_conquests', ['name'], unique=True)
    op.create_table('fiends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('was_captured', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('species_conquest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_conquest_id'], ['species_conquests.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_fiends_id'), 'fiends', ['id'], unique=False)
    op.create_index(op.f('ix_fiends_name'), 'fiends', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fiends_name'), table_name='fiends')
    op.drop_index(op.f('ix_fiends_id'), table_name='fiends')
    op.drop_table('fiends')
    op.drop_index(op.f('ix_area_conquests_name'), table_name='area_conquests')
    op.drop_index(op.f('ix_area_conquests_id'), table_name='area_conquests')
    op.drop_table('area_conquests')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_species_conquests_name'), table_name='species_conquests')
    op.drop_index(op.f('ix_species_conquests_id'), table_name='species_conquests')
    op.drop_table('species_conquests')
    op.drop_index(op.f('ix_special_fiends_name'), table_name='special_fiends')
    op.drop_index(op.f('ix_special_fiends_id'), table_name='special_fiends')
    op.drop_table('special_fiends')
    op.drop_index(op.f('ix_original_creations_name'), table_name='original_creations')
    op.drop_index(op.f('ix_original_creations_id'), table_name='original_creations')
    op.drop_table('original_creations')
    # ### end Alembic commands ###

# op.execute("""
# ALTER TABLE area_conquests
# DROP CONSTRAINT area_conquests_zone_id_fkey,
# ADD CONSTRAINT area_conquests_zone_id_fkey
# FOREIGN KEY (zone_id) REFERENCES zones(id)
# ON UPDATE CASCADE ON DELETE CASCADE
# """)
