"""

Revision ID: c3582fa18871
Revises: 0a747a0d7de2
Create Date: 2024-11-03 18:44:52.670135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3582fa18871'
down_revision: Union[str, None] = '0a747a0d7de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rewards_item_id_fkey', 'rewards', type_='foreignkey')
    op.create_foreign_key(None, 'rewards', 'items', ['item_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.create_foreign_key('rewards_item_id_fkey', 'rewards', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
