"""

Revision ID: d1cc46a72814
Revises: e3513e04ad66
Create Date: 2024-11-05 23:27:16.816805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cc46a72814'
down_revision: Union[str, None] = 'e3513e04ad66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_conquest_rewards', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('fiend_rewards', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('original_creation_rewards', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('species_conquest_rewards', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species_conquest_rewards', 'quantity')
    op.drop_column('original_creation_rewards', 'quantity')
    op.drop_column('fiend_rewards', 'quantity')
    op.drop_column('area_conquest_rewards', 'quantity')
    # ### end Alembic commands ###
