"""

Revision ID: ddc1f7d38300
Revises: 8edcb3b4ef8e
Create Date: 2024-11-03 18:21:23.718928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc1f7d38300'
down_revision: Union[str, None] = '8edcb3b4ef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_type_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'item_types', ['type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_type_id_fkey', 'items', 'item_types', ['type_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
