"""

Revision ID: e164f41ed754
Revises: 9382847f01c6
Create Date: 2024-11-05 22:39:24.704634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e164f41ed754'
down_revision: Union[str, None] = '9382847f01c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('fiend_id', sa.Integer(), nullable=False))
    op.drop_index('ix_rewards_id', table_name='rewards')
    op.create_foreign_key(None, 'rewards', 'fiends', ['fiend_id'], ['id'], onupdate='CASCADE')
    op.drop_column('rewards', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.create_index('ix_rewards_id', 'rewards', ['id'], unique=False)
    op.drop_column('rewards', 'fiend_id')
    # ### end Alembic commands ###
