"""

Revision ID: e3513e04ad66
Revises: 42534484a5a9
Create Date: 2024-11-05 22:47:42.876375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3513e04ad66'
down_revision: Union[str, None] = '42534484a5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unique_fiends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_unique_fiends_id'), 'unique_fiends', ['id'], unique=False)
    op.create_index(op.f('ix_unique_fiends_name'), 'unique_fiends', ['name'], unique=True)
    op.drop_index('ix_special_fiends_id', table_name='special_fiends')
    op.drop_index('ix_special_fiends_name', table_name='special_fiends')
    op.drop_table('special_fiends')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_fiends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='special_fiends_pkey'),
    sa.UniqueConstraint('image_url', name='special_fiends_image_url_key')
    )
    op.create_index('ix_special_fiends_name', 'special_fiends', ['name'], unique=True)
    op.create_index('ix_special_fiends_id', 'special_fiends', ['id'], unique=False)
    op.drop_index(op.f('ix_unique_fiends_name'), table_name='unique_fiends')
    op.drop_index(op.f('ix_unique_fiends_id'), table_name='unique_fiends')
    op.drop_table('unique_fiends')
    # ### end Alembic commands ###
