"""

Revision ID: e7720a6bd0e8
Revises: 716c859e8f88
Create Date: 2024-11-03 14:42:25.468246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7720a6bd0e8'
down_revision: Union[str, None] = '716c859e8f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('area_conquests_creation_reward_key', 'area_conquests', type_='unique')
    op.drop_column('area_conquests', 'creation_reward')
    op.drop_column('area_conquests', 'commons_steal')
    op.drop_column('area_conquests', 'weapon_abilities')
    op.drop_column('area_conquests', 'defeat_reward')
    op.drop_column('area_conquests', 'rare_steal')
    op.drop_column('area_conquests', 'protection_abilities')
    op.drop_constraint('original_creations_creation_reward_key', 'original_creations', type_='unique')
    op.drop_column('original_creations', 'creation_reward')
    op.drop_column('original_creations', 'commons_steal')
    op.drop_column('original_creations', 'weapon_abilities')
    op.drop_column('original_creations', 'defeat_reward')
    op.drop_column('original_creations', 'rare_steal')
    op.drop_column('original_creations', 'protection_abilities')
    op.drop_constraint('species_conquests_creation_reward_key', 'species_conquests', type_='unique')
    op.drop_column('species_conquests', 'creation_reward')
    op.drop_column('species_conquests', 'commons_steal')
    op.drop_column('species_conquests', 'weapon_abilities')
    op.drop_column('species_conquests', 'defeat_reward')
    op.drop_column('species_conquests', 'rare_steal')
    op.drop_column('species_conquests', 'protection_abilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species_conquests', sa.Column('protection_abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('species_conquests', sa.Column('rare_steal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('species_conquests', sa.Column('defeat_reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('species_conquests', sa.Column('weapon_abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('species_conquests', sa.Column('commons_steal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('species_conquests', sa.Column('creation_reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('species_conquests_creation_reward_key', 'species_conquests', ['creation_reward'])
    op.add_column('original_creations', sa.Column('protection_abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('original_creations', sa.Column('rare_steal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('original_creations', sa.Column('defeat_reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('original_creations', sa.Column('weapon_abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('original_creations', sa.Column('commons_steal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('original_creations', sa.Column('creation_reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('original_creations_creation_reward_key', 'original_creations', ['creation_reward'])
    op.add_column('area_conquests', sa.Column('protection_abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('area_conquests', sa.Column('rare_steal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('area_conquests', sa.Column('defeat_reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('area_conquests', sa.Column('weapon_abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('area_conquests', sa.Column('commons_steal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('area_conquests', sa.Column('creation_reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('area_conquests_creation_reward_key', 'area_conquests', ['creation_reward'])
    # ### end Alembic commands ###
