"""

Revision ID: f7829c7150b3
Revises: 3c0a30842117
Create Date: 2024-11-03 14:23:46.715846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7829c7150b3'
down_revision: Union[str, None] = '3c0a30842117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_conquests', sa.Column('reward', sa.String(), nullable=True))
    op.add_column('area_conquests', sa.Column('weapon_abilities', sa.String(), nullable=True))
    op.add_column('area_conquests', sa.Column('protection_abilities', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'area_conquests', ['reward'])
    op.add_column('original_creations', sa.Column('reward', sa.String(), nullable=True))
    op.add_column('original_creations', sa.Column('weapon_abilities', sa.String(), nullable=True))
    op.add_column('original_creations', sa.Column('protection_abilities', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'original_creations', ['reward'])
    op.add_column('species_conquests', sa.Column('reward', sa.String(), nullable=True))
    op.add_column('species_conquests', sa.Column('weapon_abilities', sa.String(), nullable=True))
    op.add_column('species_conquests', sa.Column('protection_abilities', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'species_conquests', ['reward'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species_conquests', type_='unique')
    op.drop_column('species_conquests', 'protection_abilities')
    op.drop_column('species_conquests', 'weapon_abilities')
    op.drop_column('species_conquests', 'reward')
    op.drop_constraint(None, 'original_creations', type_='unique')
    op.drop_column('original_creations', 'protection_abilities')
    op.drop_column('original_creations', 'weapon_abilities')
    op.drop_column('original_creations', 'reward')
    op.drop_constraint(None, 'area_conquests', type_='unique')
    op.drop_column('area_conquests', 'protection_abilities')
    op.drop_column('area_conquests', 'weapon_abilities')
    op.drop_column('area_conquests', 'reward')
    # ### end Alembic commands ###
