"""

Revision ID: f7b82ae01f80
Revises: f7829c7150b3
Create Date: 2024-11-03 14:35:49.182063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b82ae01f80'
down_revision: Union[str, None] = 'f7829c7150b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area_conquests', sa.Column('creation_reward', sa.String(), nullable=True))
    op.drop_constraint('area_conquests_reward_key', 'area_conquests', type_='unique')
    op.create_unique_constraint(None, 'area_conquests', ['creation_reward'])
    op.drop_column('area_conquests', 'reward')
    op.add_column('original_creations', sa.Column('creation_reward', sa.String(), nullable=True))
    op.drop_constraint('original_creations_reward_key', 'original_creations', type_='unique')
    op.create_unique_constraint(None, 'original_creations', ['creation_reward'])
    op.drop_column('original_creations', 'reward')
    op.add_column('species_conquests', sa.Column('creation_reward', sa.String(), nullable=True))
    op.drop_constraint('species_conquests_reward_key', 'species_conquests', type_='unique')
    op.create_unique_constraint(None, 'species_conquests', ['creation_reward'])
    op.drop_column('species_conquests', 'reward')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species_conquests', sa.Column('reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'species_conquests', type_='unique')
    op.create_unique_constraint('species_conquests_reward_key', 'species_conquests', ['reward'])
    op.drop_column('species_conquests', 'creation_reward')
    op.add_column('original_creations', sa.Column('reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'original_creations', type_='unique')
    op.create_unique_constraint('original_creations_reward_key', 'original_creations', ['reward'])
    op.drop_column('original_creations', 'creation_reward')
    op.add_column('area_conquests', sa.Column('reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'area_conquests', type_='unique')
    op.create_unique_constraint('area_conquests_reward_key', 'area_conquests', ['reward'])
    op.drop_column('area_conquests', 'creation_reward')
    # ### end Alembic commands ###
